name = "drea-s-online-fashion"
compatibility_date = "2026-08-18"
compatibility_flags = ["nodejs_compat"]

main = "build/server/index.js"

[assets]
directory = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "drea_db"
database_id = "cfe3feaf-678a-419b-9b1c-ffd414be571b"
